services:
  backend:
    container_name: dual-image-rdh-be
    build: 
      context: ./backend
    ports:
      - "8000:8000"

  frontend:
    container_name: dual-image-rdh-fe
    build: 
      context: ./frontend
    ports:
      - "800:80"